// Supabase connection settings

window.SUPABASE_URL = "https://fwabikzwcjaevbmubnap.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3YWJpa3p3Y2phZXZibXVibmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODczNjk4NjAsImV4cCI6MjEwMjk0NTg2MH0.QRnxPmha4tYc1NdFTjshE2_z0muuZzTZ_1oulNaPdQc";
